# Generated by Django 4.2.5 on 2023-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0004_skillpointstransactionhistory_skillpointstransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpoints',
            name='available_points',
            field=models.IntegerField(default=1000),
        ),
    ]
