# Generated by Django 4.2.5 on 2023-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0005_alter_skillpoints_available_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillpointstransactionhistory',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='skillpointstransactionhistory',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
