# Generated by Django 4.2.5 on 2023-12-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0006_skillpointstransactionhistory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillpointstransactionhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='skillpointstransactionhistory',
            name='transaction_id',
        ),
    ]
