SKILLS = [
    {"category": "Programming Languages", "name": "Python"},
    {"category": "Programming Languages", "name": "JavaScript"},
    {"category": "Programming Languages", "name": "Java"},
    {"category": "Programming Languages", "name": "C++"},
    {"category": "Web Development", "name": "HTML & CSS"},
    {"category": "Web Development", "name": "React"},
    {"category": "Web Development", "name": "Angular"},
    {"category": "Web Development", "name": "Node.js"},
    {"category": "Mobile App Development", "name": "iOS Development"},
    {"category": "Mobile App Development", "name": "Android Development"},
    {"category": "Database Management", "name": "SQL"},
    {"category": "Database Management", "name": "MongoDB"},
    {"category": "Machine Learning", "name": "TensorFlow"},
    {"category": "Machine Learning", "name": "PyTorch"},
    {"category": "Data Science", "name": "Data Analysis"},
    {"category": "Data Science", "name": "Machine Learning Algorithms"},
    {"category": "Design & Multimedia", "name": "Graphic Design"},
    {"category": "Design & Multimedia", "name": "Video Editing"},
    {"category": "Design & Multimedia", "name": "3D Modeling"},
    {"category": "Music & Audio", "name": "Music Production"},
    {"category": "Music & Audio", "name": "Audio Engineering"},
    {"category": "Music & Audio", "name": "Guitar"},
    {"category": "Music & Audio", "name": "Piano"},
    {"category": "Music & Audio", "name": "Singing"},
    {"category": "Music & Audio", "name": "Violin"},
    {"category": "Marketing & Digital Marketing", "name": "Social Media Marketing"},
    {"category": "Marketing & Digital Marketing", "name": "Search Engine Optimization (SEO)"},
    {"category": "Marketing & Digital Marketing", "name": "Email Marketing"},
    {"category": "Business & Entrepreneurship", "name": "Startup Strategies"},
    {"category": "Business & Entrepreneurship", "name": "Business Plan Writing"},
    {"category": "Business & Entrepreneurship", "name": "Financial Management"},
    {"category": "Languages", "name": "Spanish Language"},
    {"category": "Languages", "name": "French Language"},
    {"category": "Languages", "name": "Chinese Language"},
    {"category": "Health & Fitness", "name": "Yoga"},
    {"category": "Health & Fitness", "name": "Strength Training"},
    {"category": "Health & Fitness", "name": "Nutrition"},
    {"category": "Cooking & Culinary Arts", "name": "Baking"},
    {"category": "Cooking & Culinary Arts", "name": "Sushi Making"},
    {"category": "Cooking & Culinary Arts", "name": "Italian Cuisine"},
    {"category": "Arts & Crafts", "name": "Drawing"},
    {"category": "Arts & Crafts", "name": "Knitting"},
    {"category": "Arts & Crafts", "name": "Pottery"},
    {"category": "Photography", "name": "Portrait Photography"},
    {"category": "Photography", "name": "Landscape Photography"},
    {"category": "Photography", "name": "Photo Editing"},
    {"category": "Fashion & Beauty", "name": "Makeup Artistry"},
    {"category": "Fashion & Beauty", "name": "Fashion Design"},
    {"category": "Fashion & Beauty", "name": "Hair Styling"},
    {"category": "Travel & Adventure", "name": "Travel Photography"},
    {"category": "Travel & Adventure", "name": "Backpacking Tips"},
    {"category": "Gardening", "name": "Urban Gardening"},
    {"category": "Gardening", "name": "Botanical Knowledge"},
    {"category": "Pet Care", "name": "Dog Training"},
    {"category": "Pet Care", "name": "Cat Grooming"},
    {"category": "Pet Care", "name": "Pet Nutrition"},
    {"category": "Parenting", "name": "Newborn Care"},
    {"category": "Parenting", "name": "Positive Discipline"},
    {"category": "Parenting", "name": "Teenage Psychology"},
    {"category": "Personal Development", "name": "Time Management"},
    {"category": "Personal Development", "name": "Goal Setting"},
    {"category": "Personal Development", "name": "Mindfulness Meditation"},
    {"category": "Self-Defense", "name": "Krav Maga"},
    {"category": "Self-Defense", "name": "Karate"},
    {"category": "Self-Defense", "name": "Jiu-Jitsu"},
    {"category": "Finance & Investment", "name": "Stock Market Trading"},
    {"category": "Finance & Investment", "name": "Real Estate Investment"},
    {"category": "Finance & Investment", "name": "Retirement Planning"},
    {"category": "Automotive", "name": "Car Maintenance"},
    {"category": "Automotive", "name": "Motorcycle Riding"},
    {"category": "Automotive", "name": "Auto Detailing"},
    {"category": "Sports & Fitness", "name": "Basketball"},
    {"category": "Sports & Fitness", "name": "Tennis"},
    {"category": "Sports & Fitness", "name": "Swimming"},
    {"category": "Sports & Fitness", "name": "Martial Arts"},
    {"category": "Sports & Fitness", "name": "Cycling"},
    {"category": "Outdoor Activities", "name": "Hiking"},
    {"category": "Outdoor Activities", "name": "Camping"},
    {"category": "Outdoor Activities", "name": "Fishing"},
    {"category": "Outdoor Activities", "name": "Survival Skills"},
    {"category": "Home Improvement", "name": "DIY Home Repairs"},
    {"category": "Home Improvement", "name": "Plumbing"},
    {"category": "Home Improvement", "name": "Interior Design"},
    {"category": "Education & Teaching", "name": "Mathematics"},
    {"category": "Education & Teaching", "name": "Science"},
    {"category": "Education & Teaching", "name": "Language Teaching"},
    {"category": "Education & Teaching", "name": "Special Education"},
    {"category": "Education & Teaching", "name": "Online Tutoring"},
    {"category": "Business Software", "name": "Microsoft Excel"},
    {"category": "Business Software", "name": "Project Management"},
    {"category": "Business Software", "name": "Data Analytics"},
    {"category": "Business Software", "name": "Digital Marketing Tools"},
    {"category": "Art & Culture", "name": "Art History"},
    {"category": "Art & Culture", "name": "Classical Music"},
    {"category": "Art & Culture", "name": "Theater Arts"},
    {"category": "Art & Culture", "name": "Creative Writing"},
    {"category": "Art & Culture", "name": "Film Making"},
    {"category": "Art & Culture", "name": "Dance"},
    {"category": "Art & Culture", "name": "Photography Lighting"},
    {"category": "Art & Culture", "name": "Sculpture"},
    {"category": "Art & Culture", "name": "Cinematography"},
    {"category": "Art & Culture", "name": "Graphic Novels"},
    {"category": "Art & Culture", "name": "Animation"},
    {"category": "Art & Culture", "name": "Fashion Photography"},
    {"category": "Art & Culture", "name": "Visual Effects"},
    {"category": "Art & Culture", "name": "Voice Acting"},
    {"category": "Art & Culture", "name": "Sketching"},
    {"category": "Art & Culture", "name": "Oil Painting"},
    {"category": "Art & Culture", "name": "Digital Art"},
    {"category": "Art & Culture", "name": "Illustration"},
]
